### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by matheusmaximo** [honglu/aws-sqs-dlq-redriver#1]
First of all, thanks for your project.

I would suggest a small update to the readme:
https://github.com/honglu/aws-sqs-dlq-redriver#input

It says: "DLQUrl (required) - The URL of the DLQ queue."
Should be: "DLQName (required) - The name of the DLQ queue."

**Comment by honglu** [comment]
Thanks for bringing this up. The README has been fixed!
